# Intake Catalogs

Intake **catalogs are structures** which make navigating the different models, experiments, output variables etc. much easier than clicking through the folder structure. You can easily browse data in the shared folders on the jupyterhub.

In [3]:
#import necessary packages
import intake_esm
import intake
import pandas
import xarray
import gcsfs
import matplotlib as mpl
import cartopy.crs as ccrs
import warnings
#suppress some annoying future warning
warnings.filterwarnings("ignore", category=FutureWarning)

The intake catalog corresponding to the CMIP6 files  under `~/shared-tacco-ns1004k-cmip*` is

In [38]:
cmip6_catalog_path = '/mnt/tacco-ns1004k/catalogs/merged_local.json'
cmip6_catalog = intake.open_esm_datastore(cmip6_catalog_path)
cmip6_catalog

The left column are the attributes of all files included in the catalog. The 'unique' column tells you how many unique, i.e. different, versions of each attributes exist amongst the files. You can print all entries of each of the attributes to see what is available:

In [39]:
unique = local_cmip6_catalog.unique()
unique['source_id']

['TaiESM1',
 'AWI-CM-1-1-MR',
 'AWI-ESM-1-1-LR',
 'BCC-CSM2-MR',
 'BCC-ESM1',
 'CAMS-CSM1-0',
 'CAS-ESM2-0',
 'FGOALS-f3-L',
 'FGOALS-g3',
 'IITM-ESM',
 'CanESM5-1',
 'CanESM5-CanOE',
 'CanESM5',
 'CMCC-CM2-HR4',
 'CMCC-CM2-SR5',
 'CMCC-ESM2',
 'CNRM-CM6-1-HR',
 'CNRM-CM6-1',
 'CNRM-ESM2-1',
 'ACCESS-CM2',
 'ACCESS-ESM1-5',
 'E3SM-1-0',
 'E3SM-1-1-ECA',
 'E3SM-1-1',
 'EC-Earth3-AerChem',
 'EC-Earth3-CC',
 'EC-Earth3-LR',
 'EC-Earth3-Veg-LR',
 'EC-Earth3-Veg',
 'EC-Earth3',
 'FIO-ESM-2-0',
 'MPI-ESM-1-2-HAM',
 'INM-CM4-8',
 'INM-CM5-0',
 'IPSL-CM5A2-INCA',
 'IPSL-CM6A-LR-INCA',
 'IPSL-CM6A-LR',
 'KIOST-ESM',
 'MIROC-ES2H',
 'MIROC-ES2L',
 'MIROC6',
 'HadGEM3-GC31-LL',
 'HadGEM3-GC31-MM',
 'UKESM1-0-LL',
 'UKESM1-1-LL',
 'ICON-ESM-LR',
 'MPI-ESM1-2-HR',
 'MPI-ESM1-2-LR',
 'MRI-ESM2-0',
 'GISS-E2-1-G-CC',
 'GISS-E2-1-G',
 'historical',
 'piControl',
 'GISS-E2-1-H',
 'GISS-E2-2-G',
 'GISS-E2-2-H',
 'GISS-E3-G',
 'CESM2-FV2',
 'CESM2-WACCM-FV2',
 'CESM2-WACCM',
 'CESM2',
 'KACE-1-0-G',
 'GFDL-AM4',
 'GFDL-CM4',
 'GFDL-ESM4',
 'NESM3',
 'SAM0-UNICON',
 'CIESM',
 'MCM-UA-1-0',
 'NorCPM1',
 'NorESM1-F',
 'NorESM2-LM',
 'NorESM2-MM']

You can also create a **subset** of your catalog by specifying attributes through the **.search()** function

In [40]:
cat_subset = local_cmip6_catalog.search(
    experiment_id = "historical",
    member_id = "r1i1p1f1",
    table_id = "Lmon",
    variable_id = "tsl"
)
cat_subset.unique()

variable_id                                                        [tsl]
table_id                                                          [Lmon]
source_id              [TaiESM1, BCC-CSM2-MR, BCC-ESM1, FGOALS-f3-L, ...
experiment_id                                               [historical]
member_id                                                     [r1i1p1f1]
grid_label                                                      [gn, gr]
time_range             [185002-201412, 185001-192912, 193001-201412, ...
activity_id               [tacco-ns1004k-cmip, tacco-ns1004k-cmip-betzy]
institution_id         [AS-RCEC, BCC, CAS, CCCma, CSIRO-ARCCSS, CSIRO...
version                [20200218, 20181114, 20190821, 20190429, 20191...
path                   [/mnt/tacco-ns1004k-cmip/AS-RCEC/TaiESM1/histo...
dcpp_init_year                                                        []
format                                                          [netcdf]
derived_variable_id                                                   []
dtype: object

You can also **inspect** the catalog by looking at its underlying pandas dataframe.

In [41]:
local_cmip6_catalog.df

,variable_id,table_id,source_id,experiment_id,member_id,grid_label,time_range,activity_id,institution_id,version,path,dcpp_init_year,format
0,tas,Amon,TaiESM1,1pctCO2,r1i1p1f1,gn,000101-015012,tacco-ns1004k-cmip,AS-RCEC,20200225,/mnt/tacco-ns1004k-cmip/AS-RCEC/TaiESM1/1pctCO...,NaN,netcdf
1,hus,Amon,TaiESM1,abrupt-4xCO2,r1i1p1f1,gn,000101-015012,tacco-ns1004k-cmip,AS-RCEC,20200310,/mnt/tacco-ns1004k-cmip/AS-RCEC/TaiESM1/abrupt...,NaN,netcdf
2,pr,Amon,TaiESM1,abrupt-4xCO2,r1i1p1f1,gn,000101-015012,tacco-ns1004k-cmip,AS-RCEC,20200310,/mnt/tacco-ns1004k-cmip/AS-RCEC/TaiESM1/abrupt...,NaN,netcdf
3,rlut,Amon,TaiESM1,abrupt-4xCO2,r1i1p1f1,gn,000101-015012,tacco-ns1004k-cmip,AS-RCEC,20200310,/mnt/tacco-ns1004k-cmip/AS-RCEC/TaiESM1/abrupt...,NaN,netcdf
4,rlutcs,Amon,TaiESM1,abrupt-4xCO2,r1i1p1f1,gn,000101-015012,tacco-ns1004k-cmip,AS-RCEC,20200310,/mnt/tacco-ns1004k-cmip/AS-RCEC/TaiESM1/abrupt...,NaN,netcdf
...,...,...,...,...,...,...,...,...,...,...,...,...,...
849532,sosga,Omon,MCM-UA-1-0,ssp585,r1i1p1f2,gn,201501-210012,tacco-ns1004k-cmip-betzy2,UA,20190731,/mnt/tacco-ns1004k-cmip-betzy2/UA/MCM-UA-1-0/s...,NaN,netcdf
849533,thetao,Omon,MCM-UA-1-0,ssp585,r1i1p1f2,gn,201501-210012,tacco-ns1004k-cmip-betzy2,UA,20190731,/mnt/tacco-ns1004k-cmip-betzy2/UA/MCM-UA-1-0/s...,NaN,netcdf
849534,tos,Omon,MCM-UA-1-0,ssp585,r1i1p1f2,gn,201501-210012,tacco-ns1004k-cmip-betzy2,UA,20190731,/mnt/tacco-ns1004k-cmip-betzy2/UA/MCM-UA-1-0/s...,NaN,netcdf
849535,tosga,Omon,MCM-UA-1-0,ssp585,r1i1p1f2,gn,201501-210012,tacco-ns1004k-cmip-betzy2,UA,20190731,/mnt/tacco-ns1004k-cmip-betzy2/UA/MCM-UA-1-0/s...,NaN,netcdf
849536,areacella,fx,MCM-UA-1-0,ssp585,r1i1p1f2,gn,NaN,tacco-ns1004k-cmip-betzy2,UA,20190731,/mnt/tacco-ns1004k-cmip-betzy2/UA/MCM-UA-1-0/s...,NaN,netcdf

**Pandas dataframes** have the **.head()** and **.tail()** functions to inspect the first and last 5 rows.

- learn more about the pandas package and the options you have with it!

In [42]:
local_cmip6_catalog.df.head()

,variable_id,table_id,source_id,experiment_id,member_id,grid_label,time_range,activity_id,institution_id,version,path,dcpp_init_year,format
0,tas,Amon,TaiESM1,1pctCO2,r1i1p1f1,gn,000101-015012,tacco-ns1004k-cmip,AS-RCEC,20200225,/mnt/tacco-ns1004k-cmip/AS-RCEC/TaiESM1/1pctCO...,NaN,netcdf
1,hus,Amon,TaiESM1,abrupt-4xCO2,r1i1p1f1,gn,000101-015012,tacco-ns1004k-cmip,AS-RCEC,20200310,/mnt/tacco-ns1004k-cmip/AS-RCEC/TaiESM1/abrupt...,NaN,netcdf
2,pr,Amon,TaiESM1,abrupt-4xCO2,r1i1p1f1,gn,000101-015012,tacco-ns1004k-cmip,AS-RCEC,20200310,/mnt/tacco-ns1004k-cmip/AS-RCEC/TaiESM1/abrupt...,NaN,netcdf
3,rlut,Amon,TaiESM1,abrupt-4xCO2,r1i1p1f1,gn,000101-015012,tacco-ns1004k-cmip,AS-RCEC,20200310,/mnt/tacco-ns1004k-cmip/AS-RCEC/TaiESM1/abrupt...,NaN,netcdf
4,rlutcs,Amon,TaiESM1,abrupt-4xCO2,r1i1p1f1,gn,000101-015012,tacco-ns1004k-cmip,AS-RCEC,20200310,/mnt/tacco-ns1004k-cmip/AS-RCEC/TaiESM1/abrupt...,NaN,netcdf